version: '{build}'

clone_folder: c:\projects\open62541
clone_depth: 20

# Avoid building branch if it is part of a PR and built anyways
skip_branch_with_pr: true

# Fast finish (stop other builds if one fails) to speed up appveyor builds
# matrix:
#  fast_finish: true

environment:
    global:
        APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=9

    matrix:
        - CC_NAME: MinGW Makefiles
          CC_SHORTNAME: mingw
          GENERATOR: MinGW Makefiles
          FORCE_CXX: OFF
        - CC_NAME: Visual Studio 9 2008
          CC_SHORTNAME: vs2008
          GENERATOR: Visual Studio 9 2008
          FORCE_CXX: ON
        - CC_NAME: Visual Studio 12 2013
          CC_SHORTNAME: vs2013
          GENERATOR: Visual Studio 12 2013
          FORCE_CXX: OFF
        - CC_NAME: Visual Studio 15 2017
          CC_SHORTNAME: vs2017
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          GENERATOR: Visual Studio 15 2017
          FORCE_CXX: OFF
        - CC_NAME: Clang
          CC_SHORTNAME: clang-mingw
          GENERATOR: MinGW Makefiles
          FORCE_CXX: OFF

cache:
  - C:\ProgramData\chocolatey\bin -> tools/appveyor/install.ps1
  - C:\ProgramData\chocolatey\lib -> tools/appveyor/install.ps1
  - C:\tools\vcpkg\installed -> tools/appveyor/install.ps1
  #- 'c:\miktex'

init:
  - git config --global core.autocrlf input # Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail

install:
- set PATH=C:\Users\appveyor\AppData\Roaming\Python\Scripts;%PATH%
- ps: '& "./tools/appveyor/install.ps1"'

before_build:
  # Add installed tools to PATH
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  # Workaround for CMake not wanting sh.exe on PATH for MinGW (necessary for CMake 3.12.2)
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

build_script:
- ps: '& "./tools/appveyor/build.ps1"'

after_build:
  # Only push artifact if make install is defined
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\open62541-%CC_SHORTNAME%-static.zip
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\open62541-%CC_SHORTNAME%-dynamic.zip
